import { NISMModule } from '../types';

export const NISM_DATA: NISMModule[] = [
  {
    id: "module-1",
    number: 1,
    title: "Money & Transactions",
    tagline: "The Foundation: Income, Cashflow & Digital Payments",
    icon: "Wallet",
    color: "from-blue-500 to-cyan-400",
    estimated_mins: 25,
    linked_lab_id: "budgeting",
    lessons: [
      {
        id: "m1-l1",
        title: "Understanding Money & Income Types",
        summary: "Active income vs. passive income, gross vs. net salary, and tracking cash inflows.",
        content: `### What is Money?
Money serves three universal functions:
1. **Medium of Exchange:** Eliminates barter inefficiencies.
2. **Unit of Account:** Common metric to value goods & services.
3. **Store of Value:** Allows deferred purchasing power.

### Active vs. Passive Income
- **Active Income:** Cashflow directly dependent on continuous labor (Salary, Freelancing). When work halts, inflow halts.
- **Passive Income:** Cashflow produced by capital and assets (Dividends, Rental yields, FD Interest, Royalties).

### Golden Rule for Bharat:
*Never let your lifestyle expenses grow at the exact same pace as your active income increases (Lifestyle Inflation).*`,
        key_takeaways: [
          "Active income stops when labor stops; passive income compounds 24/7.",
          "Gross Salary is before statutory deductions; Net Salary is your real spendable cash.",
          "Maintaining an automated monthly ledger is step zero of financial independence."
        ],
        lab_id: "budgeting"
      },
      {
        id: "m1-l2",
        title: "Digital Payments & UPI Hygiene",
        summary: "Mastering UPI, IMPS, NEFT, and essential cybersecurity protocols for banking.",
        content: `### Digital Payments in Modern India
India leads the globe with **Unified Payments Interface (UPI)** managed by NPCI.

### The Non-Negotiable Law of UPI Safety:
> **YOU NEVER ENTER YOUR UPI PIN TO RECEIVE MONEY.**
> Entering your 4 or 6 digit PIN is EXCLUSIVELY for authorizing a DEBIT (sending money) from your bank account. Fraudsters frequently share fake QR codes claiming to send cashbacks.`,
        key_takeaways: [
          "A UPI PIN is never needed to receive money, cashbacks, or refunds.",
          "Always verify the beneficiary name on the VPA before hitting confirm.",
          "Set daily UPI spending limits in your bank app to contain security exposure."
        ],
        lab_id: "scam_radar"
      }
    ],
    quiz: [
      {
        question: "A buyer on OLX claims they sent you ₹15,000 for your used phone and asks you to enter your UPI PIN to approve the payment. What happens if you enter your PIN?",
        options: [
          "You will receive the ₹15,000 in your bank account.",
          "₹15,000 will be instantly deducted from your bank account.",
          "The transaction gets held in escrow until delivery.",
          "Your bank KYC gets verified."
        ],
        correct_index: 1,
        explanation: "Entering your UPI PIN ALWAYS authorizes a debit from your account. Fraudsters use fake QR codes and payment requests to trick victims into paying money instead of receiving it."
      },
      {
        question: "Which of the following is considered 'Passive Income'?",
        options: [
          "Overtime pay from working weekend shifts.",
          "Monthly salary from a full-time software engineering job.",
          "Quarterly dividend payouts from shares held in your portfolio.",
          "Cash tips received at a restaurant."
        ],
        correct_index: 2,
        explanation: "Dividend payouts from investments require no daily manual labor, representing true passive income generated by capital."
      }
    ]
  },
  {
    id: "module-2",
    number: 2,
    title: "Managing Your Finances",
    tagline: "Budgeting, Savings vs FD/RD, and Debt Control",
    icon: "PieChart",
    color: "from-emerald-500 to-teal-400",
    estimated_mins: 35,
    linked_lab_id: "real_return",
    lessons: [
      {
        id: "m2-l1",
        title: "The 50/30/20 Rule & Expense Auditing",
        summary: "Mastering the gold standard of personal budgeting: Needs vs Wants vs Future Wealth.",
        content: `### The 50/30/20 Budgeting Framework
Divide your net in-hand monthly salary into three clear buckets:

1. **50% for Needs (Essentials):** Rent, groceries, electricity, essential EMIs & health insurance.
2. **30% for Wants (Lifestyle):** Dining out, movies, gadgets, weekend getaways.
3. **20% for Wealth Building:** Emergency fund accumulation & automated Index SIPs.

### Pay Yourself First:
Automate your 20% investment on the day your salary arrives, rather than saving what is left at month-end!`,
        key_takeaways: [
          "Automate your 20% investment on Salary Day before spending on lifestyle.",
          "If your Needs exceed 50%, downsize fixed commitments to prevent debt traps.",
          "A budget doesn't restrict freedom; it gives you permission to spend guilt-free on your 30% wants."
        ],
        lab_id: "budgeting"
      },
      {
        id: "m2-l2",
        title: "Savings Account vs FD vs RD: The Real Return Reality",
        summary: "Why leaving money in a savings account loses wealth, and how inflation erodes Fixed Deposits.",
        content: `### Safe Fixed-Income Instruments
- **Savings Account (2.5% - 3.5% p.a.):** Liquid, but loses purchasing power against 6% inflation.
- **Fixed Deposit (6.5% - 7.5% p.a.):** Lump sum locked for capital preservation.

### The Tax & Inflation Drag:
For someone in the 30% tax bracket:
- Nominal FD Interest: **7.0%**
- Post-Tax Return: **4.9%**
- Annual Inflation: **6.0%**
- **Real Net Growth:** \`-1.1% per year!\``,
        key_takeaways: [
          "FD interest is fully taxable at your personal income slab rate.",
          "Real Return = Nominal Interest Rate - Taxes - Inflation Rate.",
          "Use FDs for 0-3 year emergency safety; use Equities/PPF for >5 year wealth creation."
        ],
        lab_id: "real_return"
      },
      {
        id: "m2-l3",
        title: "Good Debt vs Bad Debt & The Credit Card Trap",
        summary: "Understanding CIBIL credit scores, revolving credit interest rates (42% APR), and EMI traps.",
        content: `### Good Debt vs. Bad Debt
- **Good Debt:** Low interest loans for appreciating assets (Education, Home Loan).
- **Bad Debt:** High-interest loans for depreciating lifestyle toys (Credit card revolving debt, Personal loans).

### Revolving Credit Card Trap:
Credit cards charge **3.5% to 3.8% monthly (42% - 48% APR)**. Paying only the "Minimum Due" (5%) traps you in compounding interest for up to 15+ years!`,
        key_takeaways: [
          "Always pay 100% of your Total Amount Due before the statement due date.",
          "Keep credit utilization under 30% to build a 750+ CIBIL score.",
          "No-Cost EMIs often hide processing fees and eliminate cash discount advantages."
        ],
        lab_id: "debt_trap"
      }
    ],
    quiz: [
      {
        question: "If you earn ₹60,000 net salary per month, what is the recommended minimum amount you should invest under the 50/30/20 rule?",
        options: [
          "₹6,000 (10%)",
          "₹12,000 (20%)",
          "₹18,000 (30%)",
          "Whatever is left after shopping"
        ],
        correct_index: 1,
        explanation: "20% of ₹60,000 is ₹12,000. This should be automated directly into investments on salary day."
      },
      {
        question: "Why does paying only the 'Minimum Amount Due' on a credit card hurt your finances?",
        options: [
          "It improves your credit score too quickly.",
          "The remaining balance attracts 40%+ annual interest compounding daily.",
          "The bank closes your account automatically.",
          "It gives you bonus reward points."
        ],
        correct_index: 1,
        explanation: "Paying minimum due only avoids late penalties, while the remaining 95% balance accrues 40%+ interest compounding continuously."
      }
    ]
  },
  {
    id: "module-3",
    number: 3,
    title: "Financial Planning & Compounding",
    tagline: "Goal Setting, Rule of 72, SIPs & Long-Term Wealth",
    icon: "TrendingUp",
    color: "from-purple-500 to-indigo-400",
    estimated_mins: 30,
    linked_lab_id: "sip_compounding",
    lessons: [
      {
        id: "m3-l1",
        title: "The Magic of Compounding & The Rule of 72",
        summary: "How compounding turns small monthly discipline into multi-crore wealth, and the rapid doubling formula.",
        content: `### What is Compounding?
Compounding is when returns earned on capital start earning returns on themselves over time.

### The Rule of 72 Shortcut:
Divide 72 by the expected annual interest rate:
- At **6% (FD):** \`72 / 6\` = **12 Years** to double.
- At **12% (Nifty 50):** \`72 / 12\` = **6 Years** to double!

### The Staggering Cost of Delay:
Starting ₹5,000/month at **Age 20 vs Age 30** (12% CAGR till 60):
- **Age 20 Starter:** Invested: ₹24L ➔ **Final Corpus: ₹5.94 Crores!**
- **Age 30 Starter:** Invested: ₹18L ➔ **Final Corpus: ₹1.76 Crores.**
- *Cost of a 10-year delay:* Over **₹4.18 Crores lost in compounding!**`,
        key_takeaways: [
          "Time in the market matters far more than timing the market.",
          "Rule of 72 gives an instant mental check for investment doubling periods.",
          "Small amounts started in your early 20s outperform huge amounts started in your late 30s."
        ],
        lab_id: "sip_compounding"
      },
      {
        id: "m3-l2",
        title: "Systematic Investment Plans (SIP) & Mutual Funds",
        summary: "Direct vs Regular mutual funds, rupee-cost averaging, and index investing.",
        content: `### Direct vs. Regular Mutual Funds:
- **Regular Plans:** Contain hidden distributor commissions (0.5% - 1.5% every year). Over 25 years, this commission eats away 25% to 30% of your total retirement wealth!
- **Direct Plans:** Zero distributor commission. Always choose **Direct - Growth** plans!

### Rupee Cost Averaging:
When the market drops, your fixed monthly SIP buys MORE units at discount prices. When the market rallies, you buy fewer units. This eliminates market timing anxiety.`,
        key_takeaways: [
          "Always select 'Direct Plan - Growth Option' when investing in mutual funds.",
          "Never stop your SIP during a market crash; that is when wealth is accumulated at discount.",
          "Nifty 50 and S&P BSE Sensex index funds offer broad low-cost diversification across top Indian firms."
        ],
        lab_id: "sip_compounding"
      }
    ],
    quiz: [
      {
        question: "Using the Rule of 72, approximately how many years will it take for your investment to double at a 12% annual return?",
        options: ["12 Years", "6 Years", "8 Years", "7.2 Years"],
        correct_index: 1,
        explanation: "72 divided by 12 equals 6 years. At 12% annual CAGR, your capital doubles every 6 years."
      }
    ]
  },
  {
    id: "module-4",
    number: 4,
    title: "Risk, Reward & Insurance",
    tagline: "Building Your Safety Net: Emergency Fund & Protection",
    icon: "ShieldCheck",
    color: "from-amber-500 to-orange-400",
    estimated_mins: 30,
    linked_lab_id: "debt_trap",
    lessons: [
      {
        id: "m4-l1",
        title: "Building the Ironclad Emergency Fund",
        summary: "How much liquid cash to keep, where to park it, and when to touch it.",
        content: `### What is an Emergency Fund?
A liquid buffer protecting you against sudden job loss, medical emergencies, or family crises without selling investments at a loss.

### Sizing Your Buffer:
- **Salaried:** 3 to 6 Months of essential expenses.
- **Freelancers/Business:** 6 to 12 Months.

### Where to Keep It:
50% in high-interest Savings Account, 50% in Sweep-in FD / Liquid Mutual Fund.`,
        key_takeaways: [
          "An Emergency Fund is insurance for your peace of mind, not a profit generator.",
          "Never invest your emergency fund into volatile equities or locked-in schemes.",
          "Never touch your emergency fund for shopping or vacations."
        ],
        lab_id: "budgeting"
      },
      {
        id: "m4-l2",
        title: "Pure Term Life vs ULIP / Endowment Trap",
        summary: "Why you should never mix investment with insurance, and how to buy pure protection.",
        content: `### The Non-Negotiable Rule:
> **NEVER MIX INVESTMENT WITH INSURANCE.**

- **Pure Term Insurance:** For ~₹1,000/month, get **₹1.5 Crores** pure protection.
- **Endowment / ULIP Plans:** High ₹50,000+ premium for a measly ₹5L cover and dismal 4-5% return (loses to inflation!).`,
        key_takeaways: [
          "Buy Pure Term Insurance with at least 15-20x of your annual income as cover.",
          "Avoid ULIPs, Money-Back, and Endowment policies pushed by bank relationship managers.",
          "Have a personal family health insurance policy independent of corporate employer cover."
        ],
        lab_id: "insurance_matrix"
      }
    ],
    quiz: [
      {
        question: "A bank manager asks you to invest in a 'Guaranteed Money Back' insurance plan that pays you ₹10 Lakhs life cover and 5% return for ₹1 Lakh/year premium. What is the smarter alternative?",
        options: [
          "Accept the plan immediately because it gives guaranteed money back.",
          "Buy a Pure Term Insurance plan (₹1 Crore cover for ~₹10k/yr) and invest the remaining ₹90k in an Index Fund SIP.",
          "Take a personal loan to buy two of those insurance policies.",
          "Keep all cash in home safe."
        ],
        correct_index: 1,
        explanation: "Separating insurance and investment (Buy Term + Invest Difference in SIP) gives 10x higher life cover and 3x to 5x higher wealth at retirement."
      }
    ]
  },
  {
    id: "module-5",
    number: 5,
    title: "Financial Landscape & Scam Immunity",
    tagline: "Regulatory Bodies, Ponzi Schemes & Fraud Immunity",
    icon: "AlertTriangle",
    color: "from-rose-500 to-red-400",
    estimated_mins: 35,
    linked_lab_id: "scam_radar",
    lessons: [
      {
        id: "m5-l1",
        title: "The Guardians of Bharat's Financial System",
        summary: "Understanding RBI, SEBI, IRDAI, PFRDA and how to file formal grievance complaints.",
        content: `### Regulatory Framework in India:
1. **RBI:** Regulates Banks, NBFCs, UPI, and Lending Apps. (Banking Ombudsman).
2. **SEBI:** Regulates Stock Exchanges, Brokers, Mutual Funds. (SCORES 2.0).
3. **IRDAI:** Regulates Insurance companies. (Bima Bharosa).
4. **PFRDA:** Regulates NPS and Pension schemes.`,
        key_takeaways: [
          "Never deal with financial entities that do not hold a valid SEBI/RBI registration.",
          "If a bank or broker does not resolve your complaint in 30 days, file on the RBI Ombudsman or SEBI SCORES portal.",
          "Check broker registration numbers directly on SEBI's official portal before transferring funds."
        ],
        lab_id: "scam_radar"
      },
      {
        id: "m5-l2",
        title: "The Scam Immunity Manual: Ponzi, Telegram & Deepfakes",
        summary: "Spotting high-yield investment fraud, fake stock tipsters, and pump-and-dump traps.",
        content: `### The 5 Red Flags of Every Financial Fraud:
1. **The Word 'Guaranteed' on High Returns:** No legitimate market investment offers guaranteed 2% daily or 20% monthly returns.
2. **High-Pressure Urgency:** *"Only 5 slots left in VIP Telegram group!"*
3. **Unregulated Payment Channels:** Demanding money via personal UPI handles or crypto.
4. **Task-Based Part-Time Job Scams:** "Like YouTube videos for ₹2,000".
5. **Emergency Cyber Helpline:** In case of fraud, immediately call **1930** or visit cybercrime.gov.in!`,
        key_takeaways: [
          "If an investment sounds too good to be true, it is 100% a scam.",
          "SEBI-registered Research Analysts (RA) never guarantee returns or handle client funds directly.",
          "Report cyber financial fraud immediately at the National Cyber Crime Helpline 1930 within the golden hour."
        ],
        lab_id: "scam_radar"
      }
    ],
    quiz: [
      {
        question: "What is the emergency helpline number in India to report immediate cyber financial fraud and freeze stolen funds?",
        options: ["100", "1930", "1091", "112"],
        correct_index: 1,
        explanation: "1930 is the national Cyber Financial Fraud Helpline operated by the Ministry of Home Affairs to freeze fraudulent transactions during the golden hour."
      }
    ]
  }
];
