"""
NISM Financial Literacy Course for Bharat - Official Structured Curriculum
5 Core Modules with rich practical lessons, takeaways, and quiz challenges.
"""

NISM_MODULES = [
    {
        "id": "module-1",
        "number": 1,
        "title": "Money & Transactions",
        "tagline": "The Foundation: Income, Cashflow & Digital Payments",
        "icon": "Wallet",
        "color": "from-blue-500 to-cyan-400",
        "estimated_mins": 25,
        "lessons": [
            {
                "id": "m1-l1",
                "title": "Understanding Money & Income Types",
                "summary": "Active income vs. passive income, gross vs. net salary, and tracking cash inflows.",
                "content": """### What is Money?
Money serves three universal purposes:
1. **Medium of Exchange:** Eliminates the inefficiencies of barter.
2. **Unit of Account:** Standard measure of the value of goods and services.
3. **Store of Value:** Allows wealth to be saved and spent in the future.

### Active vs. Passive Income
- **Active Income:** Earnings derived directly from physical or intellectual labor (e.g., Monthly Salary, Freelance Fees, Daily Wages). If you stop working, the cashflow stops immediately.
- **Passive Income:** Cashflow generated from assets you own without daily active labor (e.g., Mutual Fund Dividends, Rental Income, Fixed Deposit Interest, Royalties).

### Key Rule for Bharat:
*Never let your lifestyle expenses grow at the exact same pace as your active income increases (Lifestyle Inflation).*""",
                "key_takeaways": [
                    "Active income stops when labor stops; passive income generates wealth 24/7.",
                    "Gross Salary is before deductions (PF, Professional Tax, TDS); Net In-Hand Salary is what actually hits your bank account.",
                    "Maintaining a simple monthly inflow-outflow ledger is the first step of wealth creation."
                ],
                "lab_id": "budgeting"
            },
            {
                "id": "m1-l2",
                "title": "Digital Payments & UPI Hygiene",
                "summary": "Mastering UPI, IMPS, NEFT, and essential cybersecurity protocols for banking.",
                "content": """### Digital Payments in Modern India
India is the world leader in real-time digital transactions powered by the **Unified Payments Interface (UPI)** managed by the NPCI.

### Payment Rails Compared:
- **UPI:** Instant 24/7 peer-to-peer and merchant payments up to ₹1 Lakh to ₹5 Lakhs depending on category.
- **IMPS:** Instant 24/7 interbank electronic fund transfer.
- **NEFT & RTGS:** High-value corporate & scheduled settlement channels.

### The Golden Rule of UPI Safety:
> **YOU NEVER ENTER YOUR UPI PIN TO RECEIVE MONEY.**
> Entering your 4 or 6 digit PIN is EXCLUSIVELY for authorizing a DEBIT (sending money) from your bank account.""",
                "key_takeaways": [
                    "A UPI PIN is never required to receive money, cashback, or refunds.",
                    "Always verify the beneficiary name on the UPI handle before clicking confirm.",
                    "Set daily UPI transaction limits in your banking app to mitigate theft risk."
                ],
                "lab_id": "scam_radar"
            }
        ],
        "quiz": [
            {
                "question": "A buyer on OLX claims they sent you ₹15,000 for your used bicycle and asks you to enter your UPI PIN to approve the payment. What happens if you enter your PIN?",
                "options": [
                    "You will receive the ₹15,000 in your bank account.",
                    "₹15,000 will be instantly deducted from your bank account.",
                    "The transaction gets held in escrow until delivery.",
                    "Your bank KYC gets verified."
                ],
                "correct_index": 1,
                "explanation": "Entering your UPI PIN ALWAYS authorizes a debit from your account. Fraudsters use fake QR codes and payment requests to trick victims into paying money instead of receiving it."
            },
            {
                "question": "Which of the following is considered 'Passive Income'?",
                "options": [
                    "Overtime pay from working weekend shifts.",
                    "Monthly salary from a full-time software engineering job.",
                    "Quarterly dividend payouts from shares held in your portfolio.",
                    "Cash tips received at a restaurant."
                ],
                "correct_index": 2,
                "explanation": "Dividend payouts from investments require no daily manual labor, representing true passive income generated by capital."
            }
        ]
    },
    {
        "id": "module-2",
        "number": 2,
        "title": "Managing Your Finances",
        "tagline": "Budgeting, Savings vs FD/RD, and Debt Control",
        "icon": "PieChart",
        "color": "from-emerald-500 to-teal-400",
        "estimated_mins": 35,
        "lessons": [
            {
                "id": "m2-l1",
                "title": "The 50/30/20 Rule & Expense Auditing",
                "summary": "Mastering the gold standard of personal budgeting: Needs vs Wants vs Future Wealth.",
                "content": """### The 50/30/20 Budgeting Framework
Originated by financial experts, this framework divides your net in-hand monthly salary into three non-negotiable buckets:

1. **50% for Needs (Essentials):**
   - Rent / Mortgage EMI
   - Groceries, Utilities, Electricity
   - Basic Commute / Fuel
   - Minimum Loan Repayments & Essential Insurance

2. **30% for Wants (Lifestyle):**
   - Dining out, weekend trips, movies
   - Gadgets, subscriptions (Netflix/Spotify)
   - Shopping & leisure

3. **20% for Savings & Investments (Wealth Building):**
   - Emergency Fund accumulation
   - Monthly SIP in Index / Mutual Funds
   - PPF / EPF / National Pension Scheme contributions

### Why Most People Fail:
Most people spend first, and save whatever is left over (which is usually zero). The secret is to **Pay Yourself First**: Invest 20% on the day your salary arrives!""",
                "key_takeaways": [
                    "Automate your 20% investment on Salary Day before spending on lifestyle.",
                    "If your 'Needs' exceed 50%, downsize fixed costs (cheaper rent, renegotiate EMIs).",
                    "A budget does not restrict freedom; it gives you permission to spend guilt-free on your 30% wants."
                ],
                "lab_id": "budgeting"
            },
            {
                "id": "m2-l2",
                "title": "Savings Account vs FD vs RD: The Real Return Reality",
                "summary": "Why leaving money in a savings account loses wealth, and how inflation erodes Fixed Deposits.",
                "content": """### Safe Fixed-Income Instruments
- **Savings Account (2.5% - 3.5% p.a.):** Highly liquid, but guaranteed to lose purchasing power against 5-6% inflation.
- **Fixed Deposit / FD (6.5% - 7.5% p.a.):** Lump sum locked for a fixed tenure (7 days to 10 years).
- **Recurring Deposit / RD (6.5% - 7.2% p.a.):** Fixed monthly deposit ideal for building short-term capital.

### The Tax & Inflation Drag on FDs:
If you are in the 30% tax bracket:
- Nominal FD Interest: **7.0%**
- Post-Tax Return: `7.0% - (30% of 7.0%)` = **4.9%**
- Inflation Rate: **6.0%**
- **Real Wealth Growth:** `4.9% - 6.0% = -1.1% per year!`

*Conclusion: FDs are great for emergency funds and short-term capital protection, but cannot create long-term wealth.*""",
                "key_takeaways": [
                    "FD interest is fully taxable at your personal income slab rate.",
                    "Real Return = Nominal Interest Rate - Taxes - Inflation Rate.",
                    "Use FDs for 0-3 year goals and Emergency Funds; use Equities/PPF for >5 year goals."
                ],
                "lab_id": "real_return"
            },
            {
                "id": "m2-l3",
                "title": "Good Debt vs Bad Debt & The Credit Card Trap",
                "summary": "Understanding CIBIL credit scores, revolving credit interest rates (42% APR), and EMI traps.",
                "content": """### Good Debt vs. Bad Debt
- **Good Debt:** Low interest rate loans taken to acquire assets that appreciate or increase earning capacity (e.g., Education Loan, reasonable Home Loan).
- **Bad Debt:** High-interest loans taken to purchase depreciating consumer items (e.g., Personal loans for vacations, No-Cost EMI for latest smartphone, Revolving Credit Card balance).

### The Revolving Credit Card Trap:
Credit cards charge **3.5% to 3.8% per month**, which translates to **42% to 48% APR (Annual Percentage Rate)**. Paying only the "Minimum Amount Due" (usually 5%) ensures that interest compounds on the rest, taking up to 15+ years to pay off a single gadget!""",
                "key_takeaways": [
                    "Always pay 100% of your Total Amount Due on credit cards before the due date.",
                    "Never exceed 30% credit utilization ratio to maintain a 750+ CIBIL credit score.",
                    "No-Cost EMIs often hide processing fees and eliminate cash discount advantages."
                ],
                "lab_id": "debt_trap"
            }
        ],
        "quiz": [
            {
                "question": "If you earn ₹60,000 net salary per month, what is the recommended minimum amount you should invest under the 50/30/20 rule?",
                "options": [
                    "₹6,000 (10%)",
                    "₹12,000 (20%)",
                    "₹18,000 (30%)",
                    "Whatever is left after shopping"
                ],
                "correct_index": 1,
                "explanation": "20% of ₹60,000 is ₹12,000. This should be automated directly into investments on salary day before allocating for wants."
            },
            {
                "question": "Why does paying only the 'Minimum Amount Due' on a credit card hurt your finances?",
                "options": [
                    "It improves your credit score too quickly.",
                    "The remaining balance attracts 40%+ annual interest compounding daily.",
                    "The bank closes your account automatically.",
                    "It gives you bonus reward points."
                ],
                "correct_index": 1,
                "explanation": "Paying minimum due only prevents late fees, while the remaining 95% balance accrues aggressive 40%+ interest, trapping you in a debt spiral."
            }
        ]
    },
    {
        "id": "module-3",
        "number": 3,
        "title": "Financial Planning & Compounding",
        "tagline": "Goal Setting, Rule of 72, SIPs & Long-Term Wealth",
        "icon": "TrendingUp",
        "color": "from-purple-500 to-indigo-400",
        "estimated_mins": 30,
        "lessons": [
            {
                "id": "m3-l1",
                "title": "The Magic of Compounding & The Rule of 72",
                "summary": "How compounding turns small monthly discipline into multi-crore wealth, and the rapid doubling formula.",
                "content": """### What is Compounding?
Albert Einstein reportedly called compound interest the *"Eighth Wonder of the World"*. Compounding is when your interest earns interest on itself over time.

Formula: `A = P * (1 + r/n)^(nt)`

### The Rule of 72 (Mental Math Shortcut):
To find out how many years it takes for your investment to double, divide 72 by the expected annual interest rate:
- At **6% (Fixed Deposit):** `72 / 6` = **12 Years** to double.
- At **12% (Nifty 50 Index Fund):** `72 / 12` = **6 Years** to double!
- At **18% (High Growth Equities):** `72 / 18` = **4 Years** to double!

### The Staggering Cost of Delay:
Starting a ₹5,000/month SIP at **Age 20 vs Age 30** at 12% return till Age 60:
- **Starter at Age 20 (40 years):** Total Invested: ₹24 Lakhs ➔ **Final Corpus: ₹5.94 Crores!**
- **Starter at Age 30 (30 years):** Total Invested: ₹18 Lakhs ➔ **Final Corpus: ₹1.76 Crores.**
- *Cost of a 10-year delay:* Over **₹4.18 Crores lost in compounding!**""",
                "key_takeaways": [
                    "Time in the market matters far more than timing the market.",
                    "Rule of 72 gives an instant mental check for investment doubling periods.",
                    "Small amounts started in your early 20s outperform huge amounts started in your late 30s."
                ],
                "lab_id": "sip_compounding"
            },
            {
                "id": "m3-l2",
                "title": "Systematic Investment Plans (SIP) & Mutual Funds",
                "summary": "Direct vs Regular mutual funds, rupee-cost averaging, and index investing.",
                "content": """### What is an Index Fund / Mutual Fund?
A Mutual Fund pools money from thousands of investors to buy a diversified basket of stocks, bonds, or commodities managed by professionals.

### Direct vs. Regular Mutual Funds:
- **Regular Plans:** Contain hidden distributor commissions (0.5% - 1.5% every year forever). Over 25 years, this commission eats away 25% to 30% of your total retirement wealth!
- **Direct Plans:** Zero distributor commission. 100% of your money works for you. Always choose **Direct - Growth** plans!

### Rupee Cost Averaging via SIP:
When the market crashes, your fixed monthly SIP buys MORE units at cheaper prices. When the market rallies, you buy fewer units at higher prices. This automatically lowers your average cost per unit without guessing market tops and bottoms.""",
                "key_takeaways": [
                    "Always select 'Direct Plan - Growth Option' when investing in mutual funds.",
                    "Never stop your SIP during a market crash; that is when wealth is created by accumulating cheap units.",
                    "Nifty 50 and S&P BSE Sensex index funds offer broad low-cost diversification across India's top companies."
                ],
                "lab_id": "sip_compounding"
            }
        ],
        "quiz": [
            {
                "question": "Using the Rule of 72, approximately how many years will it take for your investment to double at a 12% annual return?",
                "options": [
                    "12 Years",
                    "6 Years",
                    "8 Years",
                    "7.2 Years"
                ],
                "correct_index": 1,
                "explanation": "72 divided by 12 equals 6 years. At 12% annual CAGR, your capital doubles every 6 years."
            },
            {
                "question": "Why should you choose 'Direct' mutual fund plans instead of 'Regular' plans?",
                "options": [
                    "Direct plans give guaranteed government returns.",
                    "Direct plans have zero distributor commission, saving you up to 30% of your corpus over decades.",
                    "Direct plans allow daily stock trading.",
                    "Regular plans are illegal in India."
                ],
                "correct_index": 1,
                "explanation": "Direct plans bypass distributor commissions (TER difference of 0.5%-1.5% p.a.), compounding into tens of lakhs of extra wealth over a multi-decade horizon."
            }
        ]
    },
    {
        "id": "module-4",
        "number": 4,
        "title": "Risk, Reward & Insurance",
        "tagline": "Building Your Safety Net: Emergency Fund & Protection",
        "icon": "ShieldCheck",
        "color": "from-amber-500 to-orange-400",
        "estimated_mins": 30,
        "lessons": [
            {
                "id": "m4-l1",
                "title": "Building the Ironclad Emergency Fund",
                "summary": "How much liquid cash to keep, where to park it, and when to touch it.",
                "content": """### What is an Emergency Fund?
An Emergency Fund is a liquid financial buffer designed to protect you against catastrophic life events (job loss, medical emergency, sudden vehicle repair) without forcing you to sell investments at a loss or take 36% personal loans.

### Sizing Your Emergency Fund:
- **Salaried with stable job:** **3 to 6 Months** of essential monthly expenses (Rent + EMIs + Food + Utilities + Insurance).
- **Freelancers / Business owners:** **6 to 12 Months** of essential expenses.

### Where to Park It?
- 50% in a high-interest Savings Account (Instant ATM access).
- 50% in an Instant-Redemption Liquid Mutual Fund or Sweep-in Bank FD.""",
                "key_takeaways": [
                    "An Emergency Fund is insurance for your peace of mind, not a profit generator.",
                    "Never invest your emergency fund into volatile equities or locked-in schemes.",
                    "Never touch your emergency fund for shopping, vacations, or lifestyle upgrades."
                ],
                "lab_id": "budgeting"
            },
            {
                "id": "m4-l2",
                "title": "Pure Term Life vs ULIP / Endowment Trap",
                "summary": "Why you should never mix investment with insurance, and how to buy pure protection.",
                "content": """### The Golden Rule of Insurance:
> **NEVER MIX INVESTMENT WITH INSURANCE.**

### Term Insurance vs. ULIP / Endowment Plans:
- **Pure Term Insurance:** For ~₹800 to ₹1,200 / month, a 25-year-old gets **₹1 Crore to ₹1.5 Crores** pure life coverage. If you survive the term, you get ₹0 back, but your dependents are 100% financially protected if tragedy strikes.
- **Endowment / ULIP Plans:** Pay ₹50,000 / year for a measly ₹5 Lakh cover with a dismal 4-5% return (lower than inflation!).

### Health Insurance is Non-Negotiable:
A single major hospitalization in India can easily cost ₹5 Lakhs - ₹15 Lakhs, instantly wiping out years of hard-earned equity savings. Buy a dedicated individual/family floater health insurance with adequate Super Top-Up cover.""",
                "key_takeaways": [
                    "Buy Pure Term Insurance with at least 15-20x of your annual income as cover.",
                    "Avoid ULIPs, Money-Back, and Endowment policies pushed by bank relationship managers.",
                    "Do not rely solely on corporate employer health insurance; have a personal health policy."
                ],
                "lab_id": "insurance_matrix"
            }
        ],
        "quiz": [
            {
                "question": "A bank manager asks you to invest in a 'Guaranteed Money Back' insurance plan that pays you ₹10 Lakhs life cover and 5% return for ₹1 Lakh/year premium. What is the smarter alternative?",
                "options": [
                    "Accept the plan immediately because it gives guaranteed money back.",
                    "Buy a Pure Term Insurance plan (₹1 Crore cover for ~₹10k/yr) and invest the remaining ₹90k in an Index Fund SIP.",
                    "Take a personal loan to buy two of those insurance policies.",
                    "Keep all cash in home safe."
                ],
                "correct_index": 1,
                "explanation": "Separating insurance and investment (Buy Term + Invest Difference in SIP) gives 10x higher life cover and 3x to 5x higher wealth at retirement."
            }
        ]
    },
    {
        "id": "module-5",
        "number": 5,
        "title": "Financial Landscape & Scam Immunity",
        "tagline": "Regulatory Bodies, Ponzi Schemes & Fraud Immunity",
        "icon": "AlertTriangle",
        "color": "from-rose-500 to-red-400",
        "estimated_mins": 35,
        "lessons": [
            {
                "id": "m5-l1",
                "title": "The Guardians of Bharat's Financial System",
                "summary": "Understanding RBI, SEBI, IRDAI, PFRDA and how to file formal grievance complaints.",
                "content": """### Regulatory Framework in India:
1. **RBI (Reserve Bank of India):** Regulates Banks, NBFCs, UPI, Currency, and Lending apps. Operates the Integrated Banking Ombudsman for consumer complaints.
2. **SEBI (Securities & Exchange Board of India):** Regulates Stock Exchanges, Brokers (Zerodha, Groww), Mutual Funds, and Portfolio Managers. Operates the **SCORES 2.0** grievance portal.
3. **IRDAI (Insurance Regulatory & Development Authority):** Regulates Life & General Health Insurance companies. Operates **Bima Bharosa**.
4. **PFRDA (Pension Fund Regulatory & Development Authority):** Regulates National Pension System (NPS) and Atal Pension Yojana (APY).

### Grievance Escalation Hierarchy:
Entity Customer Care ➔ Principal Nodal Officer (30 days) ➔ Sector Ombudsman (RBI/SEBI/IRDAI) with binding legal authority!""",
                "key_takeaways": [
                    "Never deal with financial entities that do not hold a valid SEBI/RBI registration.",
                    "If a bank or broker does not resolve your complaint in 30 days, file on the RBI Ombudsman or SEBI SCORES portal.",
                    "Check broker registration numbers directly on SEBI's official portal before transferring funds."
                ],
                "lab_id": "scam_radar"
            },
            {
                "id": "m5-l2",
                "title": "The Scam Immunity Manual: Ponzi, Telegram & Deepfakes",
                "summary": "Spotting high-yield investment fraud, fake stock tipsters, and pump-and-dump traps.",
                "content": """### The 5 Red Flags of Every Financial Fraud:
1. **The Word 'Guaranteed' on High Returns:** No legitimate market investment offers guaranteed 2% daily or 20% monthly returns. Government 10-Yr bond yield is ~7% p.a. Anything promising 2x-3x that with zero risk is a Ponzi fraud.
2. **High-Pressure Urgency:** *"Only 5 slots left in VIP Telegram group! Invest in next 30 minutes!"*
3. **Unregulated Payment Channels:** Asking for money via personal UPI handles, crypto addresses, or foreign gaming apps rather than registered Indian broker escrow accounts.
4. **Task-Based / Part-Time Job Scams:** *"Like 5 YouTube videos and earn ₹2,000/day, then deposit ₹10,000 for VIP merchant tasks."*
5. **AI Deepfake Finfluencers:** Manipulated videos of famous billionaires (Mukesh Ambani, Ratan Tata, Narayana Murthy) endorsing secret algorithmic trading apps.""",
                "key_takeaways": [
                    "If an investment sounds too good to be true, it is 100% a scam.",
                    "SEBI-registered Research Analysts (RA) never guarantee returns or handle client funds directly.",
                    "Report cyber financial fraud immediately at the National Cyber Crime Helpline **1930** or cybercrime.gov.in within the golden hour."
                ],
                "lab_id": "scam_radar"
            }
        ],
        "quiz": [
            {
                "question": "A Telegram channel called 'NSE_VIP_PROFIT_CALLS' guarantees 15% weekly profit and asks you to transfer ₹25,000 to a personal UPI ID. What should you do?",
                "options": [
                    "Transfer ₹5,000 first to test if they are real.",
                    "Block, report the channel as fraud, and never send money.",
                    "Share the link with family and friends.",
                    "Ask for their Aadhaar card copy to verify."
                ],
                "correct_index": 1,
                "explanation": "Guaranteed weekly profits and personal UPI transfers are hallmarks of classic pump-and-dump/Ponzi scams. Legitimate SEBI registered brokers never trade on Telegram or guarantee returns."
            },
            {
                "question": "What is the emergency helpline number in India to report immediate cyber financial fraud and freeze stolen funds?",
                "options": [
                    "100",
                    "1930",
                    "1091",
                    "112"
                ],
                "correct_index": 1,
                "explanation": "1930 is the national Cyber Financial Fraud Helpline operated by the Ministry of Home Affairs to freeze fraudulent transactions during the golden hour."
            }
        ]
    }
]
